### ISSUE TITLE
腾讯云函数443报错，且调用失败

### ISSUE THREAD

**Issue by miyuren** [morning-start/auto_sign#1]

**Comment by morning-start** [comment]
截图 @goodisthebest

**Comment by morning-start** [comment]
用python3.6不要用3,7

**Comment by kelthezad** [comment]
我用的python3.6也报错
![image](https://user-images.githubusercontent.com/102723394/167239889-aef75750-bd67-48b0-8564-4117fa696792.png)

**Comment by morning-start** [comment]
@kelthezad1  你config.json文件必填的没填，看我文档中的[配置](https://github.com/morning-start/auto_sign#%E9%85%8D%E7%BD%AE)
