### ISSUE TITLE
腾讯云函数报错

### ISSUE THREAD

**Issue by kelthezad** [morning-start/auto_sign#2]
![image](https://user-images.githubusercontent.com/102723394/167240003-260b2b65-e435-45a9-b15d-891f1b741fce.png)

**Comment by morning-start** [comment]
这个没关系，右下角，切回旧版，不影响签到

![image](https://user-images.githubusercontent.com/76601464/167241000-f960cd1d-489a-4769-ab9d-c0e8d6e1a1fc.png)
