### ISSUE TITLE
都已经设置好了但是还是不能部署

### ISSUE THREAD

**Issue by kelthezad** [morning-start/auto_sign#3]
![image](https://user-images.githubusercontent.com/102723394/167262098-43e060c8-4914-4657-9a8d-d5f24fb32eb3.png)
![image](https://user-images.githubusercontent.com/102723394/167262132-e0cace79-d650-4f2d-8c96-e5a4fdf0c6a2.png)

**Comment by morning-start** [comment]
去我的仓库复制去，https://github.com/morning-start/auto_sign/blob/main/%E4%BA%91%E5%87%BD%E6%95%B0/config.json
