### ISSUE TITLE
如何选选择

### ISSUE THREAD

**Issue by 8848taijing** [morning-start/auto_sign#5]
应该复制哪几个顺序是什么样的啊应该不是把代码全部复制吧

**Comment by 8848taijing** [comment]
没有学过phython，不是很看得懂

**Comment by morning-start** [comment]
看不懂就全复制，用不到的功能不填就成。看我写的文档里的[安装](https://github.com/morning-start/XueXiTong#%E5%AE%89%E8%A3%85)

**Comment by morning-start** [comment]
不是必填的不会有报错
